craigslist_app/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings


from craigslist.views import AnnouncementListView, \
    AddAnnouncementView, CategoryAnnouncementView, LoginView, LogoutView,\
    RegisterUserView, UserAnnouncementView, AnnouncementUpdateView, \
    AnnouncementDeleteView, UserProfileView, AnnouncementDetailView, \
    ReservationCreateView, UserReservationsView, TransactionCreateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', AnnouncementListView.as_view(), name="index"),
    path(
        'add-announcement/',
        AddAnnouncementView.as_view(),
        name="add-announcement"),
    path('announcement/<pk>/', AnnouncementDetailView.as_view(),
         name="announcement"),
    path('edit-announcement/<int:pk>', AnnouncementUpdateView.as_view(),
         name="edit-announcement"),
    path('delete-announcement/<int:pk>', AnnouncementDeleteView.as_view(),
         name="delete-announcement"),
    path('category/<int:category_id>', CategoryAnnouncementView.as_view(),
         name="category-announcement"),
    path('my-announcements', UserAnnouncementView.as_view(),
         name="my-announcements"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('register/', RegisterUserView.as_view(), name="register"),
    path('my-profile/', UserProfileView.as_view(), name="my-profile"),
    path('book-announcement/', ReservationCreateView.as_view(),
         name="book-announcement"),
    path('my-reservations/', UserReservationsView.as_view(),
         name="my-reservations"),
    path('confirm/', TransactionCreateView.as_view(), name="confirm"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

craigslist/models.py
from django.db import models
from django.contrib.auth import get_user_model
from phonenumber_field.modelfields import PhoneNumberField
from django.db.models.signals import post_save
from django.dispatch import receiver

User = get_user_model()

STATUS = (
    (1, 'nowe'),
    (2, 'zaakceptowane'),
    (3, 'odrzucone'),
    (4, 'zarezerwowane'),
    (5, 'sprzedane')
)


class Category(models.Model):
    """
    Stores a single category.
    """
    category_name = models.CharField(max_length=64, unique=True)

    @property
    def category(self):
        """
        Return category name as string
        """
        return "{}".format(self.category_name)

    def __str__(self):
        return self.category


class Announcement(models.Model):
    """
    Stores a single announcement, related to :model:`craigslist.Category` and
    :model:`auth.User`.
    """
    title = models.CharField(max_length=128)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    user_who_added = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.IntegerField(choices=STATUS, default=1)
    image = models.ImageField(upload_to='staticfiles/%Y/%m/%d')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Profile(models.Model):
    """
    Extend :model:`auth.User`.
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    city = models.CharField(max_length=30, blank=True)
    street = models.CharField(max_length=30, blank=True)
    zip_code = models.CharField(max_length=6, blank=True)
    phone = PhoneNumberField(blank=True, null=True, unique=True)

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        """
        Create user profile after create user
        """
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        """
        Save profile instance
        """
        instance.profile.save()


class Reservation(models.Model):
    """
    Stores a single reservation, related to
    :model:`craigslist.Announcement` and
    :model:`craigslist.User`.
    """
    announcement = models.ForeignKey(Announcement, on_delete=models.CASCADE)
    reserved_by_user = models.ForeignKey(User, on_delete=models.CASCADE,
                                         related_name="reservation")


class Transaction(models.Model):
    """
    Stores a single transaction, related to
    :model:`auth.User` and
    :model:`auth.User`.
    """
    seller = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name="seller")
    buyer = models.ForeignKey(User, on_delete=models.CASCADE,
                              related_name="buyer")

craigslist/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from django.views.generic import FormView, \
    ListView, UpdateView, DeleteView, DetailView
from django.contrib.auth import get_user_model, authenticate, login, logout
from django.urls import reverse_lazy
from .forms import AnnouncementForm, LoginForm,\
    RegisterUserForm, UserForm, ProfileForm
from .models import Announcement, Category, STATUS, Reservation, Transaction
from django.contrib.auth.models import User as AppUser
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib import messages
from django.utils.translation import gettext as _

User = get_user_model()


class AnnouncementListView(ListView):
    """
    Display list all announcements with status = 2 ('zaakceptowane')
    """
    model = Announcement
    template_name = 'index.html'
    context_object_name = 'announcements'

    def get_queryset(self):
        """
        Return the list of announcements for this view filter by status.
        """
        return Announcement.objects.\
            filter(status=2).order_by('created_at').reverse()


class CategoryAnnouncementView(View):
    """
    Display list all announcements filter by category.
    """
    def get(self, request, category_id):
        """
        Handle GET requests: to display category announcements list.
        """
        category = get_object_or_404(Category, id=category_id)
        announcements = Announcement.objects.\
            filter(category_id=category_id, status=2).\
            order_by('created_at').reverse()
        return render(request=request,
                      template_name="category_announcements.html",
                      context={
                          "category": category,
                          "announcements": announcements,
                      })


class UserAnnouncementView(LoginRequiredMixin, View):
    """
    Display list all announcements filter by user_who_added.
    """
    login_url = reverse_lazy('login')

    def get(self, request):
        """
        Handle GET requests: to display user announcements list.
        """
        user = request.user
        announcements = Announcement.objects.filter(user_who_added=user)
        return render(request=request,
                      template_name="user_announcements.html",
                      context={
                          "announcements": announcements,
                          "statuses": STATUS
                      })


class AddAnnouncementView(LoginRequiredMixin, FormView):
    """
    Display view to add new announcement.
    """
    template_name = 'form.html'
    success_url = reverse_lazy('index')
    form_class = AnnouncementForm
    login_url = reverse_lazy('login')

    def form_valid(self, form):
        """
        Create new announcement object with the passed
        POST variables.
        """
        title = form.cleaned_data['title']
        description = form.cleaned_data['description']
        price = form.cleaned_data['price']
        category = form.cleaned_data['category']
        user_who_added = self.request.user
        image = form.cleaned_data['image']
        Announcement.objects.create(
            title=title,
            description=description,
            price=price,
            category=category,
            user_who_added=user_who_added,
            image=image,
        )
        messages.add_message(self.request, messages.SUCCESS,
                             _('Ogłoszenie zostało dodane. '
                               'Zanim pojawi się na stronie głównej musi '
                               'zostać zaakceptowane przez Administratora')
                             )
        redirect_site = super().form_valid(form)
        return redirect_site


class AnnouncementUpdateView(LoginRequiredMixin,
                             UserPassesTestMixin,
                             UpdateView):
    """
    Display view to update announcement.
    """
    model = Announcement
    form_class = AnnouncementForm
    success_url = reverse_lazy('my-announcements')
    template_name_suffix = '_update_form'
    login_url = reverse_lazy('login')

    def test_func(self):
        """
        Check if request user is user who added announcement to update
        """
        obj = self.get_object()
        return obj.user_who_added == self.request.user


class AnnouncementDeleteView(LoginRequiredMixin,
                             UserPassesTestMixin,
                             DeleteView):
    """
    View to delete announcement.
    """
    model = Announcement
    success_url = reverse_lazy('my-announcements')
    login_url = reverse_lazy('login')

    def test_func(self):
        """
        Check if request user is user who added announcement to delete
        """
        obj = self.get_object()
        return obj.user_who_added == self.request.user


class LoginView(View):
    """
    Display view to log in user.
    """
    def get(self, request):
        """
        Handle GET requests: to display log in form.
        """
        if self.request.user.is_authenticated:
            messages.\
                add_message(request, messages.SUCCESS,
                            _('Jesteś już zalogowany!'))
            return redirect('index')
        else:
            form = LoginForm()
            return render(request, 'login_form.html', {"form": form})

    def post(self, request):
        """
        Handle POST requests: to authenticate user.
        """
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.add_message(request, messages.SUCCESS,
                                     _('Zalogowano poprawnie!'))
                return redirect('index')
            else:
                form.add_error(None, 'Niepoprawny login lub hasło')

        context = {
            'form': form
        }
        return render(request, 'login_form.html', context)


class AnnouncementDetailView(DetailView):
    """
    Display view single announcement.
    """
    model = Announcement


class LogoutView(View):
    """
    View to log out user from app.
    """
    def get(self, request):
        """
        Handle GET requests: to log out user from app.
        """
        logout(request)
        messages.add_message(request, messages.SUCCESS,
                             _('Wylogowano z systemu!'))
        return redirect('index')


class RegisterUserView(FormView):
    """
    Display view to register user in app.
    """
    template_name = 'form.html'
    success_url = reverse_lazy('index')
    form_class = RegisterUserForm

    def form_valid(self, form):
        """
        Create new user object with the passed
        POST variables.
        """
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        AppUser.objects.create_user(
            username=username,
            password=password
        )
        redirect_site = super().form_valid(form)
        messages.add_message(self.request, messages.SUCCESS,
                             _('Zostałeś zarejestrowany! '
                               'Zaloguj się by móc dodawać ogłoszenia!'))
        return redirect_site


class UserProfileView(LoginRequiredMixin, View):
    """
    Display view with user profile.
    """
    login_url = reverse_lazy('login')

    def get(self, request):
        """
        Handle GET requests: to display user profile.
        """
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
        return render(request, 'profile.html', {
            'user_form': user_form,
            'profile_form': profile_form
        })

    def post(self, request):
        """
        Handle POST requests: to update user profile.
        """
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.add_message(request, messages.SUCCESS,
                                 _('Profil zaaktualizowany!'))
            return redirect('my-profile')
        else:
            messages.add_message(request, messages.WARNING,
                                 _('Popraw błędy w formularzu'))
        profile_form = ProfileForm(instance=request.user.profile)
        return render(request, 'profile.html', {
            'user_form': user_form,
            'profile_form': profile_form
        })


class ReservationCreateView(LoginRequiredMixin, View):
    """
    View to create new reservation object.
    """
    login_url = reverse_lazy('login')

    def post(self, request):
        """
        Handle POST requests: to create new reservation object.
        """
        announcement_id = request.POST['announcement_id']

        announcement = Announcement.objects.get(pk=announcement_id)
        announcement.status = 4
        announcement.save()

        Reservation.objects.create(
            announcement=announcement,
            reserved_by_user=self.request.user,
        )

        messages.add_message(request, messages.SUCCESS,
                             _('Przedmiot zarezerwowany u sprzedającego! '
                               'Skontaktuj się z nim '
                               'w celu realizacji transakcji')
                             )
        return redirect('index')


class UserReservationsView(LoginRequiredMixin, View):
    """
    Display list all announcements filter by reserved_by_user.
    """
    login_url = reverse_lazy('login')

craigslist/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Serwis z ogłoszeniami strona główna</title>
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    </head>
    <body class="d-flex flex-column min-vh-100">
        <!-- Navigation-->
        {% block nav %}
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href={% url 'index'%}>Serwis z ogłoszeniami</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Kategorie</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                {% for category in  static_categories %}
                                    <li><a class="dropdown-item" href={% url 'category-announcement' category_id=category.id %}>{{ category }}</a></li>
                                {% endfor %}
                            </ul>
                        </li>
                    </ul>
                    <ul class="navbar-nav d-flex mb-2 mb-lg-0 ms-lg-4">
                        <li>
                            <a href={% url 'add-announcement'%} class="nav-link" role="button" aria-expanded="false">
                                Dodaj Ogłoszenie
                            </a>
                        </li>
                        {% if  user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Witaj {{ user }}!
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li>
                                    <a href={% url 'logout' %} class="dropdown-item">Wyloguj się</a>
                                </li>
                                <li><a class="dropdown-item" href={% url 'my-announcements' %}>Twoje ogłoszenia</a></li>
                                <li><a class="dropdown-item" href={% url 'my-reservations' %}>Twoje rezerwacje</a></li>
                                <li><a class="dropdown-item" href={% url 'my-profile' %}>Profil użytkownika</a></li>
                            </ul>
                        </li>
                        {% else %}
                            <li>
                                <a class="nav-link" href={% url 'login'%} role="button" aria-expanded="false">
                                    Zaloguj się
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        {% endblock %}
        <!-- Header-->
        {% block header %}
            <header class="bg-dark py-5">
                <div class="container px-4 px-lg-5 my-5">
                    <div class="text-center text-white">
                        <h1 class="display-4 fw-bolder">Serwis z ogłoszeniami</h1>
                        {% block header_text %}
                            <p class="lead fw-normal text-white-50 mb-0">
                                Lista najnowszych ogłoszeń w serwisie
                            </p>
                        {% endblock %}
                    </div>
                </div>
            </header>
        {% endblock %}

        {% block messages %}
            <ul class="messages list-group" id="messages-list">
                {% if messages %}
                    {% for message in messages %}
                    <li class="list-group-item">
                        <div class="alert alert-{{ message.tags }} msg fade show" role="alert">{{ message }}</div>
                    </li>
                    {% endfor %}
                {% endif %}
            </ul>
        {% endblock %}
        <!-- Section-->
        <section class="pb-5">
            <div class="container px-4 px-lg-5 mt-5">
                {% block content %}
                {% endblock %}
            </div>
        </section>
        <!-- Footer-->
        <footer class="py-5 bg-dark mt-auto">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; by Tomasz Lach</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    </body>
</html>

craigslist/templates/category_announcements.html
{% extends "base.html" %}

{% block header_text %}
    <p class="lead fw-normal text-white-50 mb-0">
        Lista ogłoszeń dla kategorii {{ category }}
    </p>
{% endblock %}

{% block content %}
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
        {% for announcement in  announcements%}
            <div class="col mb-5">
                <div class="card h-100">
                    <img class="card-img-top" src="{{ announcement.image.url }}" />
                    <div class="card-body p-4">
                        <div class="text-center">
                            <h5 class="fw-bolder">{{ announcement.title }}</h5>
                            {{ announcement.price }} zł
                            <div>
                                {{ announcement.description|truncatechars:70 }}
                            </div>
                        </div>
                    </div>
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-dark mt-auto" href={% url 'announcement' pk=announcement.id %}>Zobacz ogłoszenie</a></div>
                    </div>
                </div>
            </div>
        {% empty %}
            </div>
            <div class="text-center display-4">
                Brak ogłoszeń w danej kategorii.
            </div>
        {% endfor %}
    </div>
{% endblock %}

craigslist/templates/form.html
{% extends "base.html" %}

{% block header_text %}
    <p class="lead fw-normal text-white-50 mb-0">
        Dodaj nowe ogłoszenie
    </p>
{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-dark" type="submit">
    </form>
{% endblock %}

craigslist/templates/index.html
{% extends "base.html" %}

{% block content %}
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
        {% for announcement in  announcements%}
            <div class="col mb-5">
                <div class="card h-100">
                    <img class="card-img-top" src="{{ announcement.image.url }}" />
                    <div class="card-body p-4">
                        <div class="text-center">
                            <h5 class="fw-bolder">{{ announcement.title }}</h5>
                            {{ announcement.price }} zł
                            <div>
                                {{ announcement.description|truncatechars:70 }}
                            </div>
                        </div>
                    </div>
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-dark mt-auto" href={% url 'announcement' pk=announcement.id %}>Zobacz ogłoszenie</a></div>
                    </div>
                </div>
            </div>
        {% empty %}
            </div>
            <div class="text-center display-4">
                Brak ogłoszeń.
            </div>
        {% endfor %}
    </div>
{% endblock %}

craigslist/templates/login_form.html
{% extends "base.html" %}

{% block header_text %}
    <p class="lead fw-normal text-white-50 mb-0">
        Zaloguj się by móc dodawać nowe ogłoszenia
    </p>
{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-dark" type="submit">
        <a href={% url 'register' %} class="btn btn-secondary role="button">Zarejestruj się</a>
    </form>

{% endblock %}

craigslist/templates/profile.html
{% extends "base.html" %}

{% block header_text %}
    <p class="lead fw-normal text-white-50 mb-0">
        Twoje dane w systemie
    </p>
{% endblock %}

{% block content %}
    <form method="post">
      {% csrf_token %}
      {{ user_form.as_p }}
        <h6>Dane Adresowe:</h6>
      {{ profile_form.as_p }}
        <input class="btn btn-dark" type="submit" value="Zapisz zmiany">
    </form>
{% endblock %}

craigslist/templates/user_announcements.html
{% extends "base.html" %}

{% block header_text %}
    <p class="lead fw-normal text-white-50 mb-0">
        Lista Twoich wszystkich Twoich ogłoszeń
    </p>
{% endblock %}

{% block content %}
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3">
        <ul class="list-group">
            {% for announcement in announcements%}
                <li class="list-group-item">
                    {% if announcement.get_status_display == "sprzedane" %}
                        <span class="badge badge-pill bg-success mb-1">Kupujący potwierdził otrzymanie przedmiotu</span>
                    {% endif %}
                    <div>
                        <span class="fw-bold">{{ announcement.title}}</span>
                    </div>
                    <div>
                        <span class="fw-bold">Cena:</span>
                        <span>{{ announcement.price}} zł</span>
                    </div>
                    <div>
                        <span class="fw-bold">Opis:</span>
                        <span>{{ announcement.description|truncatechars:10 }}</span>
                    </div>
                    <div>
                        <span class="fw-bold">Kategoria:</span>
                        <span>{{ announcement.category }}</span>
                    </div>
                    <div>
                        <span class="fw-bold">Status:</span>
                        <span>{{ announcement.get_status_display }}</span>
                    </div>

                    {% if announcement.status == 4 %}
                        <h5 class="fw-bold">Dane rezerwującego:</h5>
                        <div>
                            <span class="fw-bold">Nazwa Użytkownika:</span>
                            <span>{{ announcement.reservation_set.last.reserved_by_user }}</span>
                        </div>
                        <div>
                            <span class="fw-bold">Imię:</span>
                            <span>{{ announcement.reservation_set.last.reserved_by_user.first_name }}</span>
                        </div>
                        <div>
                            <span class="fw-bold">Nazwisko:</span>
                            <span>{{ announcement.reservation_set.last.reserved_by_user.last_name }}</span>
                        </div>
                        <div>
                            <span class="fw-bold">Numer telefonu:</span>
                            <span>{{ announcement.reservation_set.last.reserved_by_user.profile.phone }}</span>
                        </div>
                    {% endif %}

                    <a class="btn btn-info" href={% url 'announcement' pk=announcement.id %}>Podgląd</a>
                    {% if announcement.status == 1 or announcement.status == 2%}
                        <a class="btn btn-primary" href={% url 'edit-announcement' pk=announcement.id %}>Edytuj</a>
                        <a class="btn btn-danger" href={% url 'delete-announcement' pk=announcement.id %}>Usuń</a>
                    {% endif %}
                </li>
            {% empty %}
        </ul>
        <div class="text-center display-4">
            Nie dodałeś jeszcze żadnego ogłoszenia.
        </div>
    {% endfor %}
    </div>
{% endblock %}

craigslist/templates/user_reservations.html
{% extends "base.html" %}

{% block header_text %}
    <p class="lead fw-normal text-white-50 mb-0">
        Lista Twoich wszystkich Twoich rezerwacji
    </p>
{% endblock %}

{% block content %}
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3">
        <ul class="list-group">
            {% for reservation in reservations %}
                <li class="list-group-item">
                    {% if reservation.announcement.status == 5 %}
                        <span class="badge badge-pill bg-success mb-1">Potwierdzono otrzymanie przedmiotu</span>
                    {% endif %}
                    <h5 class="fw-bold">Ogłoszenie:</h5>
                    <div>
                        <span class="fw-bold">{{ reservation.announcement.title}}</span>
                    </div>
                    <div>
                        <span class="fw-bold">Cena:</span>
                        <span>{{ reservation.announcement.price}} zł</span>
                    </div>

                    <h5 class="fw-bold">Dane Sprzedającego:</h5>
                    <div>
                        <span class="fw-bold">Imię:</span>
                        <span>{{ reservation.announcement.user_who_added.first_name }}</span>
                    </div>
                    <div>
                        <span class="fw-bold">Nazwisko:</span>
                        <span>{{ reservation.announcement.user_who_added.last_name }}</span>
                    </div>
                    <div>
                        <span class="fw-bold">Numer telefonu:</span>
                        <span>{{ reservation.announcement.user_who_added.profile.phone }}</span>
                    </div>
                    {% if reservation.announcement.status == 4 %}
                        <div class="py-2">
                            <form name="create_station" method="post" action="{% url 'confirm' %}">
                                {% csrf_token %}
                                <input name="announcement_id" hidden value="{{ reservation.announcement.id }}">
                                <input class="btn btn-outline-dark flex-shrink-0" type="submit" value="Potwierdź otrzymanie przedmiotu"/>
                            </form>
                        </div>
                    {% endif %}
                    <a class="btn btn-info" href={% url 'announcement' pk=reservation.announcement.id %}>
                        Podgląd zarezerwowanego przedmiotu
                    </a>
                </li>
            {% empty %}
        </ul>
        <div class="text-center display-4">
            Nie zarezerwowałeś jeszcze żadnego ogłoszenia.
        </div>
    {% endfor %}
    </div>
{% endblock %}